#DES 3YR

use_WL = T

# MGCAMB MOD START: using Weyl and non-linear
wl_use_weyl = T
wl_use_non_linear = F
# MGCAMB MOD END

wl_dataset[DES] = data/DES_Y3/DES_3YR_final.dataset
#is faster than plik
wl_dataset_speed[DES] = 8 

#Use min of 40 for consistency with CMB lensing prior (but not same as DES papers)
H0_min=40

param[DES_b1] = 1.5 0.8 3 0.05 0.05
param[DES_b2] = 1.8 0.8 3 0.05 0.05
param[DES_b3] = 1.8 0.8 3 0.05 0.05
param[DES_b4] = 1.9 0.8 3 0.05 0.05
param[DES_b5] = 0
param[DES_b6] = 0

#Looks like Metacalibration is the default
param[DES_m1] = -0.006 -0.1 0.1 0.005 0.005
param[DES_m2] = -0.020 -0.1 0.1 0.005 0.005
param[DES_m3] = -0.024 -0.1 0.1 0.005 0.005
param[DES_m4] = -0.037 -0.1 0.1 0.005 0.005
prior[DES_m1] = -0.006 0.009
prior[DES_m2] = -0.020 0.008
prior[DES_m3] = -0.024 0.008
prior[DES_m4] = -0.037 0.008

param[DES_AIA] = 1 -5 5 0.2 0.2
param[DES_alphaIA] = 1 -5 5 0.2 0.2
param[DES_z0AI] = 0.62

param[DES_DzL1] = -0.009 -0.05 0.05 0.005 0.005
param[DES_DzL2] = -0.035 -0.05 0.05 0.005 0.005
param[DES_DzL3] = -0.005 -0.05 0.05 0.005 0.005
param[DES_DzL4] = -0.007 -0.05 0.1 0.005 0.005
param[DES_DzL5] = 0
param[DES_DzL6] = 0

prior[DES_DzL1] = -0.009 0.007
prior[DES_DzL2] = -0.035 0.011
prior[DES_DzL3] = -0.005 0.006
prior[DES_DzL4] = -0.007 0.006
#prior[DES_DzL5] = 0.002 0.007
#prior[DES_DzL6] = 0.002 0.008

param[DES_DzS1] = 0.0 -0.1 0.1 0.01 0.01
param[DES_DzS2] = 0.0 -0.1 0.1 0.01 0.01
param[DES_DzS3] = 0.0 -0.1 0.1 0.01 0.01
param[DES_DzS4] = 0.0 -0.1 0.1 0.01 0.01

prior[DES_DzS1] = 0.0 0.018
prior[DES_DzS2] = 0.0 0.015
prior[DES_DzS3] = 0.0 0.011
prior[DES_DzS4] = 0.0 0.017
